### ISSUE TITLE
ckan files stream should have -o|--output parameter

### ISSUE THREAD

**Issue by wardi** [DataShades/ckanext-files#4]
writing binary to stdout isn't supported in windows environments (should we ever want to support such a thing) users will expect to be able to give a file name for the output.

Also I expect problems when dumping to `stdout` instead of `stdout.buffer` because the former would need to be encoded in the system encoding, unless click.echo has some magic for handling binary data?

**Comment by wardi** [comment]
while we're at it we could add more parameters:
- seek from beginning/end of file
- limit the number of bytes streamed
- specify an output directory (instead of an output file name) and have the command create the file with the same filename as the original

**Comment by smotornyuk** [comment]
I like these suggestions. And I don't think click covers all problems of the binary output, because I once saw my shell crumped after streaming image to STDOUT
